# Generated by Django 5.2.8 on 2025-11-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_remove_trafficlog_interval_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='protocol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='total_packets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
