# Generated by Django 5.2.8 on 2025-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_trafficlog_protocol_trafficlog_total_packets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='protocol',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
